### ISSUE TITLE
Patcher sometimes stuck in finding Steam Library

### ISSUE THREAD

**Issue by r0fld4nc3** [r0fld4nc3/Stellaris-Exe-Checksum-Patcher#14]
Patcher sometimes gets stuck in trying to find the Steam Library. Unsure what is causing it. Need more reports

**Comment by FitzTack** [comment]
The log file seemed pretty sparse, so hopefully it helps. If there's anything else I can do to capture more data, please let me know.

[StellarisChecksumPatcherLog.txt](https://github.com/user-attachments/files/15512820/StellarisChecksumPatcherLog.txt)

![Screenshot](https://github.com/r0fld4nc3/Stellaris-Exe-Checksum-Patcher/assets/78160737/ddcf332d-4c0e-4531-9697-2c99803b5a56)

**Comment by r0fld4nc3** [comment]
Hi @FitzTack

Thanks for the update!

Hm indeed. In my hubris to not retain as much user info as possible it serems I've removed most useful calls and put them likely on a debug. I'll get a new version out asap and we can go from there! :) 

In the meantime, a possible fix would be to do the following.

1. Open `%localappdata/r0fld4nc3/Apps/Stellaris/ChecksumPatcher`
2. Open the `stellaris-checksum-patcher-settings.json` file
3. Paste the path to your stellaris.exe after the semi-colon.

**It is important to place the path to the .exe within the double quotes, and don't forget the comma after the closing quotation ark**
It would look like the following: `"install-dir": "O:\SteamLibrary\steamapps\common\Stellaris\stellaris.exe",`


This should, for now, fix it, as once it's saved, it will use that stored path instead of trying to find it.

**Comment by FitzTack** [comment]
It seems like my copy of C:\Users\------\AppData\Local\r0fld4nc3\Apps\Stellaris\ChecksumPatcher\stellaris-checksum-patcher-settings.json only contains the following:

`{
  "app-version": "[]"
}`

I deleted this and tried again, each time with 1.1.0-pre recreating the same settings file. I rolled back 1.0.6, and it contains the following:

`{
  "app-version": "1.0.6",
  "install-location": ""
}`

When I fill the variable with my install location, including the comma after the closing quotation like you instructed, it looks like this:

`{
  "app-version": "1.0.6",
  "install-location": "D:\Steam Library\steamapps\common\Stellaris\stellaris.exe",
}`

When I try to run the executable now, either 1.0.6 or 1.1.0-pre, I get the following Java crash output:
`Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "UI\stellaris_checksum_patcher_gui.py", line 83, in __init__
  File "UI\stellaris_checksum_patcher_gui.py", line 238, in load_configs
  File "settings\settings.py", line 35, in get_install_location
  File "settings\settings.py", line 106, in load_config
  File "settings\settings.py", line 78, in clean_save_file
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Invalid \escape: line 3 column 26 (char 53)
`

The character position referenced is the first backslash following my drive letter designation within "install-location". I have attached the log generated by the patcher during this attempt: 
[StellarisChecksumPatcherLog.txt](https://github.com/user-attachments/files/15517356/StellarisChecksumPatcherLog.txt)

**Comment by r0fld4nc3** [comment]
> It seems like my copy of C:\Users------\AppData\Local\r0fld4nc3\Apps\Stellaris\ChecksumPatcher\stellaris-checksum-patcher-settings.json only contains the following:
> 
> `{ "app-version": "[]" }`
> 
> I deleted this and tried again, each time with 1.1.0-pre recreating the same settings file. I rolled back 1.0.6, and it contains the following:
> 
> `{ "app-version": "1.0.6", "install-location": "" }`
> 
> When I fill the variable with my install location, including the comma after the closing quotation like you instructed, it looks like this:
> 
> `{ "app-version": "1.0.6", "install-location": "D:\Steam Library\steamapps\common\Stellaris\stellaris.exe", }`
> 
> When I try to run the executable now, either 1.0.6 or 1.1.0-pre, I get the following Java crash output: `Traceback (most recent call last): File "main.py", line 5, in <module> File "UI\stellaris_checksum_patcher_gui.py", line 83, in __init__ File "UI\stellaris_checksum_patcher_gui.py", line 238, in load_configs File "settings\settings.py", line 35, in get_install_location File "settings\settings.py", line 106, in load_config File "settings\settings.py", line 78, in clean_save_file File "json\__init__.py", line 293, in load File "json\__init__.py", line 346, in loads File "json\decoder.py", line 337, in decode File "json\decoder.py", line 353, in raw_decode json.decoder.JSONDecodeError: Invalid \escape: line 3 column 26 (char 53) `
> 
> The character position referenced is the first backslash following my drive letter designation within "install-location". I have attached the log generated by the patcher during this attempt: [StellarisChecksumPatcherLog.txt](https://github.com/user-attachments/files/15517356/StellarisChecksumPatcherLog.txt)
> 
> EDIT: Strangely enough, even though I had deleted the application and its files and allowed them to regenerate multiple times, this time it worked. I had to escape all of the backslashes, but it ran without a hitch. I hope this intermittent behavior isn't the result of my installation environment, but hopefully some good comes from this data.

Ahhh the backslash escape sequence, that's the one that broke it.
I have to look as well why it is saving it like that.

And yes that was the best course to let it auto generate, so at least there's a starting base for it.
I was going to suggest you try escaping the backslashes but you got there first! Good work!

I'll look at improving that as well, and not, the whole weirdness of the behaviour isn't something on your end, it isn't the first time someone has gotten stuck in the process of finding the steam library, which I find odd because I cannot replicate at all.

Thanks for the effort and hopefully it is working now (semi)!

**Comment by twothirtyfive** [comment]
Just to be clear to anyone reading this who may not know, escaping backslashes is done by adding an additional backslash in front of every backslash.

So it would look like this:
`"install-dir": "O:\\SteamLibrary\\steamapps\\common\\Stellaris\\stellaris.exe",`

**Comment by Aqu4tic2** [comment]
Heyo,

Had this same issue, managed to get it to work eventually. Was trying to run it from Downloads folder but it just wouldn't work. Ended up deleting the log and settings.json files.

I moved the patcher to the Stellaris install folder and ran it to generate the settings.json file, then opened the settings.json and added the "install-dir" and "save-games-dir" paths manually with escaping backslashes as explained above (thanks btw, I had no idea). Then I opened the exe and hit patch executable and it worked.

Hope this helps.

**Comment by r0fld4nc3** [comment]
Hey @Aqu4tic2,

Thanks for the update!

I believe it could've been Windows being Windows not letting it run from the Downloads folder as I can run mine from there without issue, or the Desktop for that matter.

Ideally you place it somewhere easily accessible so you don't have to manually go to the game folder every time. I hope once I fix it, it won't be so clunky! But I am glad it also now worked for you!

**Comment by madagent** [comment]
I'm still having issues getting this to work. It just hangs.

[2024-06-06 10:47:21] [INFO]: Checking for Stellaris Checksum Patcher update...
[2024-06-06 10:47:22] [INFO]: No updates found.
[2024-06-06 10:47:24] [INFO]: Patching from game installation.
[2024-06-06 10:47:24] [INFO]: Locating game install...
[2024-06-06 10:47:24] [INFO]: Acquiring Stellaris installation...
[2024-06-06 10:47:24] [INFO]: Getting installation details for game: Stellaris
[2024-06-06 10:47:24] [INFO]: Acquiring Steam installation...
[2024-06-06 10:47:24] [INFO]: Getting available Steam Libraries...


I edited my json file to look like:

{
  "app-version": "1.1.0.pre",
  "install-dir": "G:\\SteamLibrary\\steamapps\\common\\Stellaris\\stellaris.exe",
  "save-games-dir": "",
  "patched-block": "",
  "exe-name": ""
}

I have the patcher .exe in the Stellaris folder.  Tried running it from there and from my downloads folder.  Same deal where it hangs.

**Comment by twothirtyfive** [comment]
Can you share the contents of your `StellarisChecksumPatcherLog.txt` file?

**Comment by madagent** [comment]
Not much to go on...

[2024-06-06 10:47:21] [INFO]: Debug:             False
[2024-06-06 10:47:21] [INFO]: App Version:       [1, 1, 0, 'pre']
[2024-06-06 10:47:21] [INFO]: Target System:     Windows
[2024-06-06 10:47:21] [INFO]: Program Data Path: C:\Users\jeffr\AppData\Local
[2024-06-06 10:47:21] [INFO]: Config Folder:     C:\Users\jeffr\AppData\Local\r0fld4nc3\Apps\Stellaris\ChecksumPatcher
[2024-06-06 10:47:21] [INFO]: Checking for Stellaris Checksum Patcher update...
[2024-06-06 10:47:22] [INFO]: No updates found.
[2024-06-06 10:47:24] [INFO]: Patching from game installation.
[2024-06-06 10:47:24] [INFO]: Locating game install...
[2024-06-06 10:47:24] [INFO]: Acquiring Stellaris installation...
[2024-06-06 10:47:24] [INFO]: Getting installation details for game: Stellaris
[2024-06-06 10:47:24] [INFO]: Acquiring Steam installation...
[2024-06-06 10:47:24] [INFO]: Getting available Steam Libraries...




















[2024-06-06 10:49:36] [INFO]: Quitting Application.

**Comment by r0fld4nc3** [comment]
Heya @madagent sorry for the troubles.
Could you try 2 things here:
1. Remove the executable name from the "install-dir" entry
> {
> "app-version": "1.1.0.pre",
> "install-dir": "G:\SteamLibrary\steamapps\common\Stellaris\stellaris.exe",
> "save-games-dir": "",
> "patched-block": "",
> "exe-name": ""
> }
Above is how you have it, simply remove the stellaris.exe from there so it looks like
```
{
"app-version": "1.1.0.pre",
"install-dir": "G:\SteamLibrary\steamapps\common\Stellaris",
"save-games-dir": "",
"patched-block": "",
"exe-name": ""
}
```

If it still doesn't work properly, write the `stellaris.exe` into the "exe-name" entry between the quotes. Just the file name.

If it still doesn't work
Could you try just deleting the config file (json), letting the app regenerate it and then doing the above steps? I'm positive with doing the steps described above it should work.

I haven't yet been able to tackle the way it finds the installation path and steam path so apologies for taking longer on that front.

**Comment by madagent** [comment]
That made it work.  I had to remove the stellaris.exe to get it to work.  My JSON file looked like below for anyone else needing help:

{
  "app-version": "1.1.0.pre",
  "install-dir": "G:\\SteamLibrary\\steamapps\\common\\Stellaris",
  "save-games-dir": "",
  "patched-block": "",
  "exe-name": ""
}

I went to look at the JSON after the patcher worked and the file was updated and looked like:

{
  "app-version": "1.1.0.pre",
  "install-dir": "G:\\SteamLibrary\\steamapps\\common\\Stellaris\\stellaris.exe",
  "save-games-dir": "",
  "patched-block": "488B12488D0D1B0FB201E8BE0895018BF833C0",
  "exe-name": "stellaris.exe"
}

**Comment by r0fld4nc3** [comment]
Perfect!
You really just needed to remove the `stellaris.exe` from the `install-dir` path,  and possibly add `stellaris.exe` to `exe-name` and that should really be it 😄 

Thank you for updating us on the matter!

**Comment by Syliss85** [comment]
i am unable to get it to work even with the above fixes and the json log file isnt any help as the others previously have posted mine looks pretty much the same

**Comment by Barragek0** [comment]
`{
  "app-version": "1.1.0.pre",
  "install-dir": "G:\\SteamLibrary\\steamapps\\common\\Stellaris\\stellaris.exe",
  "save-games-dir": "",
  "patched-block": "488B12488D0DB31FC401E85E63A6018BF833C0",
  "exe-name": "stellaris.exe"
}`

was having the same issue and changing the settings file as described above worked for me.

**Comment by r0fld4nc3** [comment]
Hey @senshi-x glad to hear it worked!
I've finally been able to have a Linux version working so now I can have it on Windows & Linux.
Next focus will be to add some more robust support to it as well as finally digging in on the Steam Library issues, because I can't remember at the moment now if I've tweaked it to a point where it works better!

Thanks for the update and for using it!

**Comment by Queenofdragons6** [comment]
I've been having this issue today, and none of the above worked.

**Comment by sudatime** [comment]
> That made it work. I had to remove the stellaris.exe to get it to work. My JSON file looked like below for anyone else needing help:
> 
> { "app-version": "1.1.0.pre", "install-dir": "G:\SteamLibrary\steamapps\common\Stellaris", "save-games-dir": "", "patched-block": "", "exe-name": "" }
> 
> I went to look at the JSON after the patcher worked and the file was updated and looked like:
> 
> { "app-version": "1.1.0.pre", "install-dir": "G:\SteamLibrary\steamapps\common\Stellaris\stellaris.exe", "save-games-dir": "", "patched-block": "488B12488D0D1B0FB201E8BE0895018BF833C0", "exe-name": "stellaris.exe" }

thinks!!

**Comment by KureitKale** [comment]
Was having this same issue with the most recent release, tried some of the fixes, and ended up with what is seemingly a... new issue? It has persisted even after deleting and redownloading all files. Not really sure what's going on here, so hoping somebody has some insight...

![Image](https://github.com/user-attachments/assets/7231ea72-e039-4ce0-9145-caa4edeeec84)

**Comment by r0fld4nc3** [comment]
Oh, what!? @KureitKale

Ok that's really odd, never had that happen.

Could you post your log file somewhere?

Additionally, could you run it again with a run argument `-d` so it runs in debug? Maybe I can gather more information that way.

Also be sure to delete the files in your `C:\Users\user\AppData\Local\r0fld4nc3\Apps\Stellaris\ChecksumPatcher` if you want to try with totally fresh settings.

**Comment by r0fld4nc3** [comment]
I'll have to double check how to handle multiple libraries, which seems to be what is happening.

**Comment by xADDBx** [comment]
> I'll have to revisit how to handle multiple libraries, which seems to be what is happening.

I've previously used the `GameFinder` library to locate games, which has worked pretty well (at least nobody complained); so maybe looking at that code could help? The code is somewhat abstract, though. https://github.com/erri120/GameFinder/tree/master/src/GameFinder.StoreHandlers.Steam

**Comment by r0fld4nc3** [comment]
For anyone still interested and still following, apologies for the massive delay but I've finally been able to get around to it and I am overhauling an immense amount of the app. A lot has changed since and if you'd like to follow along there's [a lot more information and discussion going on in this branch](https://github.com/r0fld4nc3/Stellaris-Exe-Checksum-Patcher/issues/26).

There was another issue semi-related to the Steam Library being stuck, it had to do with the parsing of vdf files, [mentioned in this issue](#30 )

I've updated the [pre-release 2.0.0 page](https://github.com/r0fld4nc3/Stellaris-Exe-Checksum-Patcher/releases/tag/v2.0.0) with the most recent changes to test out how it's going so far. In summary, a lot of great improvements, perhaps not immediately noticeable but that will make this application better, easier to maintain, flexible and more expandable so perhaps we could be looking at supporting more PDX games.

For now, if anyone is still interested I'd like to hear some feedback over on the changes and if it still gets stuck finding the Steam Library.

Thank you all for your patience and support!
